/**
 * EvoFrame Core — SkillGenome
 *
 * Every agent capability in EvoFrame is expressed as a SkillGenome:
 * a versioned, lineage-tracked, fitness-scored unit of executable logic.
 * Genomes are stored on 0G Storage KV and their lineage on 0G Storage Log.
 */

// ---------------------------------------------------------------------------
// Primitive types
// ---------------------------------------------------------------------------

export type SkillId = string; // uuid-v4

export type SkillStatus =
  | "candidate" // generated by EvolutionEngine, not yet evaluated
  | "evaluating" // FitnessRunner is running tests
  | "active" // passed fitness threshold, in production use
  | "retired" // superseded by a fitter descendant
  | "rejected"; // failed fitness evaluation

export type SkillDomain =
  | "research"
  | "coding"
  | "reasoning"
  | "data-analysis"
  | "web-browsing"
  | "communication"
  | "planning"
  | "general";

// ---------------------------------------------------------------------------
// Skill parameter schema (JSON Schema subset)
// ---------------------------------------------------------------------------

export interface SkillParameter {
  name: string;
  type: "string" | "number" | "boolean" | "object" | "array";
  description: string;
  required: boolean;
  default?: unknown;
}

// ---------------------------------------------------------------------------
// Core SkillGenome — the DNA of an agent capability
// ---------------------------------------------------------------------------

export interface SkillGenome {
  /** Unique identifier for this genome instance */
  id: SkillId;

  /** Human-readable skill name, e.g. "deep-web-search" */
  name: string;

  /** Short description shown to LLMs when selecting skills */
  description: string;

  /** Domain category for pollination filtering */
  domain: SkillDomain;

  /** Semantic version — increments on every promoted mutation */
  version: string;

  /** The executable JavaScript/TypeScript function body (stringified) */
  implementation: string;

  /** Parameter schema for the skill's execute() call */
  parameters: SkillParameter[];

  /** Expected output description */
  outputDescription: string;

  // -------------------------------------------------------------------------
  // Lineage tracking (immutable after first write)
  // -------------------------------------------------------------------------

  /** ID of the genome this was mutated from. null for genesis skills */
  parentId: SkillId | null;

  /** Generation number. 0 for genesis, n+1 for each mutation */
  generation: number;

  /** Address of the agent that created this genome */
  originAgent: string;

  /** 0G Storage content hash of the parent genome at mutation time */
  parentStorageHash: string | null;

  // -------------------------------------------------------------------------
  // Fitness metrics (mutable — updated by FitnessRunner)
  // -------------------------------------------------------------------------

  /** Composite fitness score 0-100 */
  fitnessScore: number;

  /** Number of times this skill has been successfully used */
  usageCount: number;

  /** Number of times this skill caused a task failure */
  failureCount: number;

  /** Array of benchmark task IDs this skill was tested against */
  benchmarkResults: BenchmarkResult[];

  // -------------------------------------------------------------------------
  // Lifecycle metadata
  // -------------------------------------------------------------------------

  status: SkillStatus;

  /** Unix ms timestamp of genome creation */
  createdAt: number;

  /** Unix ms timestamp of last status change */
  updatedAt: number;

  /** 0G Storage KV key where this genome is stored */
  storageKey: string;

  /** Hash of the sealed inference request that generated this mutation (if any) */
  sealedInferenceAttestation: string | null;

  /** On-chain SkillRegistry contract entry tx hash (set after registration) */
  onChainTxHash: string | null;
}

// ---------------------------------------------------------------------------
// Benchmark result
// ---------------------------------------------------------------------------

export interface BenchmarkResult {
  taskId: string;
  taskDescription: string;
  passed: boolean;
  latencyMs: number;
  outputQualityScore: number; // 0-100, LLM-judged
  errorMessage?: string;
  ranAt: number; // Unix ms
}

// ---------------------------------------------------------------------------
// Mutation context — passed to EvolutionEngine to trigger a mutation
// ---------------------------------------------------------------------------

export interface MutationContext {
  parentGenome: SkillGenome;
  failureReason: string;
  failedTaskDescription: string;
  agentAddress: string;

  /** Optional additional context to guide the mutation */
  hint?: string;
}

// ---------------------------------------------------------------------------
// Evolution event — emitted after each evolution cycle step
// ---------------------------------------------------------------------------

export type EvolutionEventType =
  | "mutation_requested"
  | "candidate_generated"
  | "fitness_evaluation_started"
  | "fitness_evaluation_completed"
  | "skill_promoted"
  | "skill_rejected"
  | "skill_registered_onchain"
  | "pollination_received";

export interface EvolutionEvent {
  type: EvolutionEventType;
  skillId: SkillId;
  timestamp: number;
  data: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Config used to bootstrap EvoFrame
// ---------------------------------------------------------------------------

export interface EvoFrameConfig {
  /** Agent wallet private key (for on-chain operations) */
  agentPrivateKey: string;

  /** Human-readable agent name */
  agentName: string;

  /** Ethereum address of the SkillRegistry contract on 0G Chain */
  skillRegistryAddress: string;

  /** 0G Chain RPC URL */
  chainRpcUrl: string;

  /** 0G Storage node RPC URL */
  storageRpcUrl: string;

  /** 0G DA RPC URL */
  daRpcUrl: string;

  /** 0G Compute endpoint for sealed inference */
  computeEndpoint: string;

  /** Model to use for evolution mutations (default: qwen3.6-plus) */
  evolutionModel?: string;

  /** Minimum fitness score (0-100) for a skill to be promoted (default: 70) */
  fitnessThreshold?: number;

  /** Max number of mutation candidates generated per cycle (default: 3) */
  maxCandidatesPerCycle?: number;

  /** Whether to auto-register promoted skills on-chain (default: true) */
  autoRegisterOnChain?: boolean;
}

// ---------------------------------------------------------------------------
// Skill execution context
// ---------------------------------------------------------------------------

export interface SkillExecutionContext {
  taskDescription: string;
  agentName: string;
  previousResults: unknown[];
  memorySnapshot: Record<string, unknown>;
}

export interface SkillExecutionResult {
  success: boolean;
  output: unknown;
  latencyMs: number;
  errorMessage?: string;
  usedSkillId: SkillId;
}
