// Genome-to-Keeper Synthesis.
//
// This is the core unique workflow: every time the EvoFrame agent promotes
// a new generation of its yield-allocator SkillGenome, we translate the
// evolved strategy into a KeeperHub workflow definition, hand the prompt
// to KeeperHub's `ai_generate_workflow` endpoint, deploy the resulting
// workflow via `create_workflow`, and retire the previous generation's
// workflow once the new one is live.
//
// The synthesised workflow is parameterised on the agent's public /evaluate
// endpoint, so it can call back into the agent on every scheduled run to
// fetch the *current* allocation produced by the evolved strategy.

import { kh, KeeperHubError } from "./client.mjs";
import {
  findWorkflowFor,
  recordDeployment,
  listRetiredWorkflows,
  markCleanedUp,
} from "./registry.mjs";

// ── Endpoint constants ────────────────────────────────────────────────────
// The MCP tool names map to these REST paths. They are configurable via env
// because the public docs do not pin the exact REST shape — see
// FEEDBACK_KEEPERHUB.md for details.
const PATHS = {
  aiGenerate:    process.env.KH_PATH_AI_GENERATE   ?? "/ai/generate-workflow",
  createWorkflow: process.env.KH_PATH_CREATE_WORKFLOW ?? "/workflows/create",
  updateWorkflow: (id) => `/workflows/${encodeURIComponent(id)}`,
  deleteWorkflow: (id) => `/workflows/${encodeURIComponent(id)}`,
};

async function toManualMode({ skill, agent, causeMessage }) {
  const manualWorkflowId = (process.env.KH_REBALANCE_WORKFLOW_ID ?? "").trim() || null;
  let current = null;

  if (manualWorkflowId) {
    current = await recordDeployment({
      skillId: skill.id,
      generation: skill.generation,
      workflowId: manualWorkflowId,
      agent,
    });
  }

  const nextStep = manualWorkflowId
    ? "Linked KH_REBALANCE_WORKFLOW_ID from .env into the local registry for this generation."
    : "Set KH_REBALANCE_WORKFLOW_ID in .env to run rebalances via a manually created workflow.";

  return {
    workflowId: manualWorkflowId,
    reused: Boolean(manualWorkflowId),
    skipped: true,
    mode: "manual",
    skill,
    current,
    reason:
      "KeeperHub AI workflow synthesis endpoint is unavailable (404). " +
      `Tried REST path ${PATHS.aiGenerate}. ${nextStep}` +
      (causeMessage ? ` Cause: ${causeMessage}` : ""),
  };
}

// ── Prompt construction ───────────────────────────────────────────────────
function buildSynthesisPrompt({ skill, agent, evaluateUrl, regenerateUrl, allocationTargets }) {
  const targets = allocationTargets
    .map((t) => `  - ${t.name} on ${t.chain}: ${t.protocol} (token ${t.token}, contract ${t.contract})`)
    .join("\n");

  return [
    `Generate a KeeperHub workflow named "evoyield-${skill.name}-gen${skill.generation}".`,
    ``,
    `Context:`,
    `- This workflow is the deployment artifact for an evolved DeFi yield-allocation strategy.`,
    `- The strategy code is generated by an external AI (the EvoFrame framework on 0G).`,
    `- The current strategy generation is ${skill.generation}, fitness score ${skill.fitnessScore}/100.`,
    `- The agent that owns this strategy is "${agent}".`,
    ``,
    `Required workflow behaviour:`,
    `1. Trigger: schedule, every 1 hour. Also expose a webhook trigger so callers can force-run.`,
    `2. Step 1 — HTTP GET ${evaluateUrl}/status — fetch the agent's current skill generation and fitness.`,
    `   If fitness < 60, branch to step 6 (regenerate) and stop.`,
    `3. Step 2 — HTTP POST ${evaluateUrl}/evaluate with current on-chain APY data as JSON body.`,
    `   Expected response: { allocation: { aave, morpho, yearn, sky }, generation, fitnessScore }.`,
    `4. Step 3 — Read current balances on each target protocol:`,
    `\n${targets}`,
    `5. Step 4 — Compute deltas vs target allocation, withdraw from over-allocated, deposit into under-allocated.`,
    `   All on-chain calls must use KeeperHub managed-execution (gas estimation, nonce mgmt, MEV-safe routing).`,
    `6. Step 5 — Verification: re-read balances, fail the workflow if total deviation > 1%.`,
    `7. Step 6 — Regeneration trigger: HTTP POST ${regenerateUrl} with body { reason, fitnessScore, generation }.`,
    `   This tells the EvoFrame agent to produce a new SkillGenome and re-synthesise this workflow.`,
    ``,
    `Output strictly the workflow JSON (nodes, edges, triggers).`,
  ].join("\n");
}

function buildFallbackWorkflow({ skill, agent, regenerateUrl }) {
  const code = `
const payload = {{Webhook.data}};
const allocation = payload?.allocation ?? {};
const marketData = payload?.marketData ?? {};
const REGEN_THRESHOLD = 60;
const REGENERATE_URL = ${JSON.stringify(regenerateUrl ?? "")};

// Performance guard: if the agent's fitness has dropped below the minimum
// viable threshold, call /regenerate so EvoFrame promotes a better SkillGenome
// before executing any rebalance.  This is the KeeperHub → agent callout.
const fitnessScore = Number(payload?.fitnessScore ?? 100);
if (fitnessScore < REGEN_THRESHOLD && REGENERATE_URL) {
  let regenResult = {};
  try {
    const rResp = await fetch(REGENERATE_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        reason: \`KeeperHub workflow detected low fitness (\${fitnessScore}/100)\`,
        fitnessScore,
        generation: payload?.generation,
      }),
    });
    regenResult = rResp.ok ? await rResp.json().catch(() => ({})) : { status: rResp.status };
  } catch (e) {
    regenResult = { error: e?.message ?? String(e) };
  }
  return {
    success: false,
    regenerateTriggered: true,
    fitnessScore,
    regenResult,
    message: \`Fitness too low (\${fitnessScore}/100) — evolution triggered. Re-run after the next generation is promoted.\`,
  };
}

const protocols = ["aave", "morpho", "yearn", "sky"];
const target = Object.fromEntries(protocols.map((name) => [name, Number(allocation[name] ?? 0)]));
const total = protocols.reduce((sum, name) => sum + target[name], 0);
if (Math.abs(total - 100) > 1) throw new Error("Target allocation must sum to 100");

const rebalancePlan = protocols.map((name) => ({
  protocol: name,
  targetPct: target[name],
  marketApy: Number(marketData[\`\${name}_apy\`] ?? 0),
  action: target[name] > 0 ? "allocate" : "withdraw",
  note:
    name === "aave" ? "Aave V3 supply/withdraw leg" :
    name === "morpho" ? "Morpho supply/withdraw leg" :
    name === "yearn" ? "Yearn V3 vault deposit/withdraw leg" :
    "Sky savings deposit/withdraw leg",
}));

return {
  success: true,
  agent: ${JSON.stringify(agent)},
  generation: payload?.generation ?? ${JSON.stringify(skill.generation)},
  fitnessScore: payload?.fitnessScore ?? ${JSON.stringify(skill.fitnessScore)},
  target,
  rebalancePlan,
  message: "EvoYield rebalance plan built from webhook payload. Replace this planning node with protocol write nodes once the KeeperHub wallet is connected.",
};
`.trim();

  return {
    name: `evoyield-${skill.name}-gen${skill.generation}-owned`,
    description:
      `Owned EvoYield rebalance workflow for gen ${skill.generation}. ` +
      "Receives target allocation and builds a four-protocol distribution plan.",
    nodes: [
      {
        id: "webhook-trigger",
        type: "trigger",
        position: { x: 0, y: 0 },
        data: {
          type: "trigger",
          label: "Webhook",
          description: "Receives EvoYield allocation payload",
          config: {
            triggerType: "Webhook",
            webhookSchema: "[]",
            webhookMockRequest: "",
          },
        },
      },
      {
        id: "build-rebalance-plan",
        type: "action",
        position: { x: 320, y: 0 },
        data: {
          type: "action",
          label: "Build Rebalance Plan",
          description: "Calculates target distribution across Aave, Morpho, Yearn, and Sky",
          config: {
            actionType: "code/run-code",
            code,
            timeout: 60,
          },
        },
      },
    ],
    edges: [
      {
        id: "webhook-to-plan",
        type: "animated",
        source: "webhook-trigger",
        target: "build-rebalance-plan",
      },
    ],
  };
}

// ── Defaults — caller can override by passing options to synthesise ───────
const DEFAULT_TARGETS = [
  { name: "aave",   chain: "ethereum", protocol: "Aave V3",     token: "USDC", contract: "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2" },
  { name: "morpho", chain: "ethereum", protocol: "Morpho Blue", token: "USDC", contract: "0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFFb" },
  { name: "yearn",  chain: "ethereum", protocol: "Yearn V3",    token: "USDC", contract: "0xBe53A109B494E5c9f97b9Cd39Fe969BE68BF6204" },
  { name: "sky",    chain: "ethereum", protocol: "Sky SSR",     token: "USDS", contract: "0xa3931d71877C0E7a3148CB7Eb4463524FEc27fbD" },
];

export async function synthesiseWorkflow({
  skill,                                    // SkillGenome — the freshly promoted skill
  agent,                                    // string — agent name, used for naming the workflow
  evaluateUrl    = process.env.EVOYIELD_PUBLIC_URL,
  regenerateUrl  = (process.env.EVOYIELD_PUBLIC_URL ?? "") + "/regenerate",
  allocationTargets = DEFAULT_TARGETS,
  projectId      = process.env.KH_PROJECT_ID ?? null,
  tagId          = process.env.KH_TAG_ID ?? null,
  cleanupRetired = true,
  force          = false,
} = {}) {
  if (!skill) throw new TypeError("synthesiseWorkflow: skill is required");
  if (!evaluateUrl) {
    throw new Error(
      "EVOYIELD_PUBLIC_URL is not set. The synthesised workflow needs a public URL " +
      "to call the agent's /evaluate endpoint. Use ngrok or deploy the server.",
    );
  }

  // Skip re-synth if we already have a workflow for this generation.
  const existing = await findWorkflowFor(skill.id, skill.generation);
  if (existing && !force) {
    return { workflowId: existing, reused: true, skill };
  }

  const prompt = buildSynthesisPrompt({
    skill, agent,
    evaluateUrl: evaluateUrl.replace(/\/+$/, ""),
    regenerateUrl,
    allocationTargets,
  });

  // Step A — ask KeeperHub to generate the workflow JSON from the prompt.
  let aiResp;
  let generated;
  try {
    aiResp = await kh.post(PATHS.aiGenerate, { prompt });
  } catch (err) {
    if (err instanceof KeeperHubError && err.status === 404) {
        if (force) {
          console.warn(
            `\n⚠️  KeeperHub AI synthesis endpoint unavailable; deploying deterministic EvoYield workflow fallback.`,
          );
          generated = buildFallbackWorkflow({ skill, agent, regenerateUrl });
      } else {
      return toManualMode({ skill, agent, causeMessage: err.message });
      }
    } else {
      throw err;
    }
  }
  generated = generated ?? aiResp.workflow ?? aiResp.result?.workflow ?? aiResp;
  if (!generated || !Array.isArray(generated.nodes)) {
    throw new KeeperHubError({
      status:    502,
      endpoint:  PATHS.aiGenerate,
      requestId: null,
      body:      aiResp,
      message:   `ai_generate_workflow returned an unexpected shape (no .nodes[])`,
    });
  }

  // Step B — deploy it.
  const idempotencyKey = force
    ? `synth:${skill.id}:gen${skill.generation}:${Date.now()}`
    : `synth:${skill.id}:gen${skill.generation}`;
  const created = await kh.post(
    PATHS.createWorkflow,
    {
      name:        generated.name        ?? `evoyield-${skill.name}-gen${skill.generation}`,
      description: generated.description ?? `Auto-synthesised from SkillGenome ${skill.id} (gen ${skill.generation})`,
      projectId,
      nodes:       generated.nodes,
      edges:       generated.edges ?? [],
      enabled:     true,
    },
    { idempotencyKey },
  );

  const workflowId = created.id ?? created.workflow_id ?? created.workflow?.id;
  if (!workflowId) {
    throw new KeeperHubError({
      status:    502,
      endpoint:  PATHS.createWorkflow,
      requestId: null,
      body:      created,
      message:   "create_workflow did not return an id",
    });
  }

  await kh.patch(PATHS.updateWorkflow(workflowId), {
    name:        generated.name        ?? `evoyield-${skill.name}-gen${skill.generation}`,
    description: generated.description ?? `Auto-synthesised from SkillGenome ${skill.id} (gen ${skill.generation})`,
    projectId,
    tagId,
    nodes:       generated.nodes,
    edges:       generated.edges ?? [],
    visibility:  "private",
    enabled:     true,
  });

  // Step C — record the deployment in the local registry, retiring the previous gen.
  const current = await recordDeployment({
    skillId:    skill.id,
    generation: skill.generation,
    workflowId,
    agent,
  });

  // Step D — best-effort cleanup of older generations on KeeperHub itself.
  if (cleanupRetired) {
    const stale = await listRetiredWorkflows({ keepLast: 1 });
    for (const old of stale) {
      try {
        await kh.delete(PATHS.deleteWorkflow(old.workflowId));
        await markCleanedUp(old.workflowId);
      } catch (err) {
        // 404 = already gone; surface anything else but don't fail the synth.
        if (!(err instanceof KeeperHubError) || err.status !== 404) {
          console.warn(`[synth] failed to delete retired workflow ${old.workflowId}: ${err.message}`);
        } else {
          await markCleanedUp(old.workflowId);
        }
      }
    }
  }

  return { workflowId, reused: false, skill, current };
}

/** Subscribe to an EvoAgent's evolution events and auto-synthesise on promotion. */
export function attachAutoSynth(agentInstance, { agentName, ...opts } = {}) {
  const engine = agentInstance.getEngine();
  engine.on(async (event) => {
    if (event.type !== "skill_promoted") return;
    try {
      const promoted = agentInstance
        .listSkills()
        .find((s) => s.id === event.skillId);
      if (!promoted) return;

      console.log(
        `\n🛠  [synth] Skill promoted (gen-${promoted.generation}, fitness=${promoted.fitnessScore}). ` +
        `Synthesising matching KeeperHub workflow...`,
      );
      const out = await synthesiseWorkflow({ skill: promoted, agent: agentName, ...opts });
      if (out.skipped) {
        console.warn(`   ↳ synth skipped (${out.mode} mode): ${out.reason}`);
      } else {
        console.log(
          out.reused
            ? `   ↳ already deployed as ${out.workflowId} (reused)`
            : `   ↳ deployed as ${out.workflowId}`,
        );
      }
    } catch (err) {
      console.error(`[synth] auto-synth failed: ${err.message ?? err}`);
    }
  });
}
